# This workflow will do a clean install of node dependencies, 
# build the source code and run tests across different versions of node
# then push to my Docker Hub account
name: Node.js API builds to Docker Hub CI

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: docker build . -t $DOCKER_USERNAME/automate-api-dockerization:1.0.0
      env:
        CI: true
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.docker_password2 }}
